disabled_rules: # rule identifiers to exclude from running
  - line_length
  - unused_closure_parameter
  - function_body_length
  - type_body_length
  - force_cast
  - nesting
  - compiler_protocol_init
opt_in_rules: # some rules are only opt-in
  - empty_count
  - closure_spacing
  - force_unwrapping
  - operator_usage_whitespace
  - redundant_nil_coalescing
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
# configurable rules can be customized from this configuration file
# binary rules can set their severity level

# rules that have both warning and error levels, can set just the warning level
# implicitly
cyclomatic_complexity:
  warning: 12
  error: 20
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
